#!/usr/bin/env bash
#
# gen-electro-data.sh — rebuild godot/assets/data/electro.json from the
# animal picture pool. Run this only when you ADD or RENAME art in
# godot/assets/graphics/pools/animals/ — it overwrites any hand edits.
#
# Each `NN_name.png` (or `name.png`) becomes { "img": "<stem>", "say": "<name>" }
# where <name> is the stem with any leading "NN_" stripped and "_" -> " ".
#
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
POOL="$HERE/../godot/assets/graphics/pools/animals"
OUT="$HERE/../godot/assets/data/electro.json"

[ -d "$POOL" ] || { echo "error: $POOL not found" >&2; exit 1; }
mkdir -p "$(dirname "$OUT")"

{
  printf '{\n'
  printf '  "_comment": "Generated by tools/gen-electro-data.sh from godot/assets/graphics/pools/animals/. Hand edits are overwritten on the next run. Add a matching word to tools/gen-voice.sh so a baked clip ships.",\n'
  printf '  "pairs": [\n'
  first=1
  for f in "$POOL"/*.png; do
    [ -e "$f" ] || continue
    stem="$(basename "$f" .png)"
    say="$(printf '%s' "$stem" | sed -E 's/^[0-9]+_//; s/_/ /g')"
    [ $first -eq 1 ] && first=0 || printf ',\n'
    printf '    { "img": "%s", "say": "%s" }' "$stem" "$say"
  done
  printf '\n  ]\n}\n'
} > "$OUT"

echo "wrote $OUT ($(grep -c '"img"' "$OUT") pairs)"
